### ISSUE TITLE
Why not use propTypes directly?

### ISSUE THREAD

**Issue by bali182** [typicode/react-fake-props#1]
Just stumbled upon this library, forgive me if I'm missing something obvious. But since the component to be tested _has_ to be in scope already, why not just use it directly to get `propTypes`? Or was the data structure that `react-docgen` provides easier to inspect?

I mean:

```js
module.exports = function fakeProps(Component, { optional = false } = {}) {
  assert(Component.propTypes)
  return restOfWhatYouDidBefore(Component.propTypes, optional)
}
```

And when using it I think it would be much more obvious to do something like this:

```js
import MyComponent from './myComponent'
import fakeProps from 'react-fake-props'

const myProps = fakeProps(MyComponent)
const vDom = <MyComponent {...myProps} />
```

**Comment by typicode** [comment]
Hi @bali182,

I would've preferred this kind of API too (` fakeProps(MyComponent`) but it was kind of complicated to get all the PropTypes. Not for basic PropTypes like `PropTypes.string`, but for nested ones like `PropTypes.shape({ ... })` which return a function. Maybe there's a way.

But `react-docgen` is really great and battle tested, plus it makes it possible to support [Flow](https://flow.org/en/docs/frameworks/react/) too which is getting quite popular for React projects.

**Comment by bali182** [comment]
Ah that's understandable! Was worth asking though :)

**Comment by typicode** [comment]
> Was worth asking though :)

Definitely :)
I've updated the README too, thanks for the question.

**Comment by AndersDJohnson** [comment]
I think this would still be valuable for non-Flow users. One advantage is it would allow use of real requires/imports, which may be needed for Jest's `--findRelatedTests` functionality.
