### ISSUE TITLE
TypeError: pluginList.indexOf is not a function

### ISSUE THREAD

**Issue by dcocchia** [typicode/react-fake-props#10]
Seeing the following error when using react-fake-props: 
`TypeError: pluginList.indexOf is not a function`

Even a simple example like below will cause it:
```js
import fakeProps from 'react-fake-props'
const props = fakeProps(<file_path>)
```

It sounds like this may be coming from the react-docgen dependency:
https://github.com/reactjs/react-docgen/issues/47

I'm using `babel-jest@22.4.0`, which I believe uses a newer version of `babylon`. It sounds like this may be the same issue as above. If that dependency were upgraded, that may fix the issue.

**Comment by typicode** [comment]
Hi @dcocchia,

Thanks for the link and heads up, I've updated react-docgen as mentioned in the thread. I've published a new version if you want to give it a try (`0.2.1`)

**Comment by dcocchia** [comment]
Thanks @typicode. This seems to have fixed the above issues. I'm running into other issues now, but I'll open different bugs if I can't work my way though them.

**Comment by typicode** [comment]
Out of curiosity, what kind of issues?

**Comment by dcocchia** [comment]
Sorry for the late reply. I'm seeing all my prop-types read as `custom`. It looks like an issue more with react-docgen. I have a feeling it's due to my usage of `createClass` and `React.PropTypes`. I'm converting over both cases to see if this fixes it.
