### ISSUE TITLE
Usage with connected components (Multiple exported component definitions found)

### ISSUE THREAD

**Issue by robbporto** [typicode/react-fake-props#13]
Hi, everyone!

I have one connected component that I just want to make a smoke test in it:

```
export class SubtopicsTable extends Component {
  componentDidMount() {
    this.props.fetchSubtopics()
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(SubtopicsTable)
```

In the test, I'm rendering the component using `shallow` that is not connected with redux:

```
import React from 'react'
import { shallow } from 'enzyme'
import fakeProps from 'react-fake-props'
import path from 'path'
import { SubtopicsTable } from '../SubtopicsTable'

const initialProps = fakeProps(
  path.join(__dirname, '../SubtopicsTable.js'), {optional: true}
)

describe('(Component) SubtopicsTable', () => {
  it('renders error when exists a error', () => {
    const wrapper = shallow(<SubtopicsTable {...initialProps} />)

    expect(wrapper).toHaveLength(1)
  })
})
```

This is not working. I'm getting this error: `Multiple exported component definitions found.``

How should I proceed? I don't want to set a mock store in this component since this is just a smoke test.

**Comment by tujoworker** [comment]
Instead of:

```js

import fakeProps from 'react-fake-props'

const props = fakeProps(require.resolve('../Modal'), {
  optional: true
})
```

Do this:

```js
import fs from 'fs'
import reactDocs from 'react-docgen'
import { fakeDataForProps } from 'react-fake-props'

const source = fs.readFileSync(require.resolve('../Modal'))
const componentInfo = reactDocs.parse(
  source,
  reactDocs.resolver.findAllComponentDefinitions
)
const props = fakeDataForProps(componentInfo.props, { optional: true })
```

**Comment by tujoworker** [comment]
@robbporto But I think, the `reactDocs.resolver.findAllComponentDefinitions` part could probably be a part of **react-fake-props** in future.

**Comment by tujoworker** [comment]
@robbporto Sorry, currently **fakeDataForProps** gets not exported! Looks like this is an bug:
 ```js 
exports.fakeDataForProps = fakeDataForProps;
```
has to be this: - I guess?
 ```js 
module.exports.fakeDataForProps = fakeDataForProps;
```

**Comment by typicode** [comment]
Thanks for your patience.

@robbporto thanks to @tujoworker finding for `reactDocs.resolver.findAllComponentDefinitionsù current version (`v0.3.1`) should let you get fake props for multiple exported components. See README for usage.

Regargind `exports.fakeDataForProps = fakeDataForProps;` I suppose it was a typo.
