### ISSUE TITLE
Update react-docgen to 4.0 and add TypeScript tests

### ISSUE THREAD

**Issue by typicode** [typicode/react-fake-props#18]

**Comment by tujoworker** [comment]
I would really like this update to happen 🙏

**Comment by typicode** [comment]
Done, thanks to @mauriciosoares PR. v1 has just been published.

**Comment by tujoworker** [comment]
Awesome ❤️👏☀️

**Comment by mauriciosoares** [comment]
Just a heads up, I opened another PR. https://github.com/typicode/react-fake-props/pull/24

 I started getting some errors on my project (that might be happening with other people as well), this PR should solve the issue
