### ISSUE TITLE
react-docgen and FlowType support

### ISSUE THREAD

**Issue by mcwebb** [typicode/react-fake-props#2]
Hi @typicode,
Firstly, thanks for a great module.

Our codebase uses Flow rather than PropTypes, so I was excited to read that react-fake-props supports Flow via react-docgen. However unfortunately it doesn't seem to actually work.
I investigated and the problem seems to be that for a Flow component react-docgen does not return a `prop.type` but rather a `prop.flowType`. Thus react-fake-props doesn't know how to interpret the field.
I've tested this with the latest v2.17 and the specified v2.15 of react-docgen.

I've started working on a PR to add support for this, however I wanted to check in with you first, in case I'm missing something obvious, because it's turning out to be a bit more work than I expected since react-docgen doesn't seem to abstract the differences between PropTypes and FlowTypes, so I'll need to write that interpreter.

Cheers,
Matt

**Comment by typicode** [comment]
Hi @mcwebb,

You're right. I was assuming it would work out of the box and didn't notice the differences in react-doc-gen README.

I've updated code with what would be the beginning of Flow support.
If you're still interested to write that interpreter that would be great :)

It could be defined here:
https://github.com/typicode/react-fake-props/blob/master/src/index.js#L78-L85

And I've created an empty Component to hold all possible Flow types for testing:
https://github.com/typicode/react-fake-props/blob/master/fixtures/flow/Component.jsx

And a corresponding test file:
https://github.com/typicode/react-fake-props/blob/master/__tests__/flow.js#L7 (currently it's skipped to avoid having Travis fail)

Cheers

**Comment by mcwebb** [comment]
Fantastic, many thanks for the support. If I have time I'll give it a go next week.
Cheers.

**Comment by typicode** [comment]
Should be good now :)

**Comment by mcwebb** [comment]
You rock! thanks :)

**Comment by typicode** [comment]
it's mainly thanks to @mukeshsoni's PR :)
